1:
  length: Tiny!
  weight: Tiny!
  size: A tiny speck!
  image: default_baby.jpg
  symptoms: Nothing to show yet!
  next_appointment:
  baby_info: Too small to know!
2:
  length: Tiny!
  weight: Tiny!
  size: A tiny speck!
  image: default_baby.jpg
  symptoms: Nothing to show yet!
  next_appointment:
  baby_info: Too small to know!
3:
  length: Tiny!
  weight: Tiny!
  size: A tiny speck!
  image: default_baby.jpg
  symptoms: Nothing to show yet!
  next_appointment:
  baby_info: Too small to know!
4:
  length: Tiny!
  weight: Tiny!
  size: a Poppy Seed
  image: poppy_seed.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ¤¢ Nausea, ğŸ˜¥ Bloating]
  next_appointment:
  baby_info: Officially an embryo!
5:
  length: Tiny!
  weight: Tiny!
  size: a Sesame Seed
  image: sesame_seed.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ¤• Headaches, ğŸ˜‹ Cravings]
  next_appointment:
  baby_info: Starting to have Aheart beat!
6:
  length: Tiny!
  weight: Tiny!
  size: a Lentil
  image: lentil.jpg
  symptoms: [ğŸ¤• Headaches, ğŸ«£ Acne, ğŸ«£ Tender breasts]
  next_appointment:
  baby_info: Forming it's nose mouth and ears!
7:
  length: Tiny!
  weight: Tiny!
  size: a Blueberry
  image: blueberry.jpg
  symptoms: [ğŸ˜Ÿ Insomnia, ğŸ˜¥ Bloating, ğŸ«£ Acne]
  next_appointment: First Ultrasound and risk assessment
  baby_info: Doubling in size!
8:
  length: 1.57cm
  weight: 20 grams
  size: a Kidney Bean
  image: kidney_bean.jpg
  symptoms: [ğŸ¤¢ Nausea, ğŸ˜« Fatigue, ğŸ˜‹ Cravings]
  next_appointment: First Ultrasound and risk assessment
  baby_info: Starting to move around!
9:
  length: 2.30cm
  weight: 27 grams
  size: a Grape
  image: grape.jpg
  symptoms: [ğŸ˜¤ Mood swings, ğŸ¤¢ Nausea, ğŸ˜Ÿ Insomnia]
  next_appointment: First Ultrasound and risk assessment
  baby_info: Developing their basic anatomy!
10:
  length: 3.1cm
  weight: 35 grams
  size: a Kumquat
  image: kumquat.jpg
  symptoms: [ğŸ˜‹ Cravings, ğŸ¤• Headaches, ğŸ˜Ÿ Insomnia]
  next_appointment: First Ultrasound and risk assessment
  baby_info: Starting to bend their limbs!
11:
  length: 4.1cm
  weight: 45 grams
  size: a Fig
  image: fig.jpg
  symptoms: [ğŸ˜¥ Bloating, ğŸ¤• Headaches, ğŸ¤¢ Nausea]
  next_appointment:
  baby_info: Almost fully formed!
12:
  length: 5.4cm
  weight: 58 grams
  size: a Lime
  image: fig.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ«£ Tender breasts, ğŸ˜¥ Bloating]
  next_appointment:
  baby_info: Testing their reflexes!
13:
  length: 6.7cm
  weight: 73 grams
  size: a Peapod
  image: peapod.jpg
  symptoms: [ğŸ¤¢ Nausea, ğŸ¤• Headaches, ğŸ˜¥ Bloating]
  next_appointment:
  baby_info: Forming their fingerprints!
14:
  length: 14.7cm
  weight: 93 grams
  size: a Lemon
  image: lemo.jpg
  symptoms: [ğŸ˜¡ Irritated, ğŸ¤¢ Nausea, ğŸ˜– Backache]
  next_appointment: Your next prenatal visit!
  baby_info: Starting to use their facial muscles!
15:
  length: 33.7 cm
  weight: 785 grams
  size: an Apple
  image: apple.jpg
  symptoms: [ğŸ¤• Headaches, ğŸ«£ Tender breasts, ğŸšï¸ High sex drive]
  next_appointment:
  baby_info: Showing their gender from this week!
16:
  length: 16.7cm
  weight: 146 grams
  size: an Avocado
  image: avocado.jpg
  symptoms: [ğŸ¤¢ Nausea, ğŸ˜‹ Cravings, ğŸ˜¡ Irritated]
  next_appointment: Your next screening exam!
  baby_info: Developing their head!
17:
  length: 20.4cm
  weight: 181 grams
  size: a Turnip
  image: turnip.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜ Sad, ğŸ˜– Backache]
  next_appointment:
  baby_info: Moving their joints!
18:
  length: 22.2cm
  weight: 223 grams
  size: a Bell Pepper
  image: bell_pepper.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ¤• Headaches, ğŸ«£ Tender breasts]
  next_appointment: Ultrasound checkup!
  baby_info: Moving so much you could feel it!
19:
  length: 24.0cm
  weight: 273 grams
  size: a Heirloom Tomato
  image: heirloom_tomato.jpg
  symptoms: [ğŸ˜– Backache, ğŸ˜ Sad, ğŸ˜Š Calm]
  next_appointment: Ultrasound checkup if you haven't already!
  baby_info: Able to hear your voice!
20:
  length: 25.7cm
  weight: 331 grams
  size: a Banana
  image: banana.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜– Backache, ğŸ—² Energetic]
  next_appointment: Ultrasound checkup if you haven't already!
  baby_info: Learning how to swallow!
21:
  length: 27.4cm
  weight: 399 grams
  size: a Carrot
  image: carrot.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜‹ Cravings, ğŸ«£ Tender breasts]
  next_appointment: Ultrasound checkup if you haven't already!
  baby_info: Kicking a lot more from this week!
22:
  length: 29.0cm
  weight: 478 grams
  size: a Spaghetti Squash
  image: spaghetti_squash.jpg
  symptoms: [ğŸ˜ Sad, ğŸ˜¨ Constipation, ğŸ«£ Tender breasts]
  next_appointment: Ultrasound checkup if you haven't already!
  baby_info: Starting to look like a miniature newborn!
23:
  length: 30.6cm
  weight: 568 grams
  size: a Mango
  image: mango.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ«£ Tender breasts, ğŸ˜Š Happy]
  next_appointment:
  baby_info: Able to hear sounds more easily!
24:
  length: 32.2cm
  weight: 670 grams
  size: a Corn
  image: corn.jpg
  symptoms: [ğŸ˜ Sad, ğŸ˜Š Calm, ğŸ«£ Tender breasts]
  next_appointment: The glucose test!
  baby_info: Starting to develop baby fat!
25:
  length: 33.7 cm
  weight: 785 grams
  size: a Rutabaga
  image: rutabaga.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ¤¢ Nausea, ğŸ˜ Sad]
  next_appointment: The glucose test if you haven't already!
  baby_info: Starting to grow hair!
26:
  length: 35.1cm
  weight: 913 grams
  size: a Scallion
  image: scallion.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ«£ Tender breasts, ğŸ˜ Sad]
  next_appointment: Your next prenatal visit!
  baby_info: Starting to inhale and exhale!
27:
  length: 36.6cm
  weight: 1055 grams
  size: a Cauliflower
  image: cauliflower.jpg
  symptoms: [ğŸ˜– Backache, ğŸ˜¨ Constipation, ğŸ˜¡ Irritated]
  next_appointment: The glucose test if you haven't already!
  baby_info: Developing a very active brain!
28:
  length: 37.6cm
  weight: 1210 grams
  size: an Eggplant
  image: eggplant.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜– Backache, ğŸ«£ Acne]
  next_appointment: A checkup every 2 weeks!
  baby_info: Developing their eyesight!
29:
  length: 39.3cm
  weight: 1379 grams
  size: a Butternut Squash
  image: butternut_squash.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜¨ Constipation, ğŸ˜¡ Irritated]
  next_appointment: A checkup every 2 weeks!
  baby_info: Developing their lungs and muscles!
30:
  length: 40.5cm
  weight: 1559 grams
  size: a Cabbage
  image: cabbage.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ«£ Tender breasts, ğŸ—² Energetic]
  next_appointment: A checkup every 2 weeks!
  baby_info: Growing very quickly!
31:
  length: 41.8cm
  weight: 1751 grams
  size: a Coconut
  image: coconut.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ˜– Backache, ğŸ˜‹ Cravings]
  next_appointment: A checkup every 2 weeks!
  baby_info: Turning their head side to side!
32:
  length: 43.0cm
  weight: 1953 grams
  size: a Jicama
  image: jicama.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜– Backache, ğŸ«£ Tender breasts]
  next_appointment: A checkup every 2 weeks!
  baby_info: Gaining weight quickly!
33:
  length: 44.1cm
  weight: 2162 grams
  size: a Pineapple
  image: pineapple.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ—² Energetic, ğŸ˜« Fatigue]
  next_appointment: A checkup every 2 weeks!
  baby_info: Developing their skull!
34:
  length: 45.3cm
  weight: 2377 grams
  size: a Cantaloupe
  image: cantaloupe.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ˜¥ Bloating, ğŸ˜ Sad]
  next_appointment: A checkup every 2 weeks!
  baby_info: Developing their central nervouse system!
35:
  length: 46.3cm
  weight: 2595 grams
  size: a Honeydew Melon
  image: honeydew_melon.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜– Backache, ğŸ«£ Acne]
  next_appointment: A checkup every 2 weeks!
  baby_info: Moving a lot more!
36:
  length: 47.3cm
  weight: 2813 grams
  size: a Romaine Lettuce
  image: romaine_lettuce.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ¤• Headaches, ğŸšï¸ High sex drive]
  next_appointment: A checkup every 2 weeks!
  baby_info: Gaining an ounce a day!
37:
  length: 48.3cm
  weight: 3028 grams
  size: a Swiss Chard
  image: swiss_chard.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ«£ Acne, ğŸšï¸ High sex drive]
  next_appointment: A checkup every week!
  baby_info: Developing their lungs and brains!
38:
  length: 49.3cm
  weight: 3236 grams
  size: a Leek
  image: leek.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜Š Happy, ğŸ—² Energetic]
  next_appointment: A checkup every week!
  baby_info: Growing quickly!
39:
  length: 50.1cm
  weight: 3435 grams
  size: a Mini Watermelon
  image: watermelon.jpg
  symptoms: [ğŸ˜Š Calm, ğŸ˜– Backache, ğŸ˜¡ Irritated]
  next_appointment: A checkup every week!
  baby_info: Considered full term!
40:
  length: 51.0cm
  weight: 3619 grams
  size: a Small Pumpkin
  image: pumpkin.jpg
  symptoms: [ğŸ˜« Fatigue, ğŸ˜– Backache, ğŸ˜¨ Constipation]
  next_appointment: A checkup every week!
  baby_info: Considered fully developed!
default:
  length:
  weight:
  size:
  image: default_baby.jpg
  symptoms:
  next_appointment:
  baby_info:
